### ISSUE TITLE
给Yolov5或者Yolov4更换backbone

### ISSUE THREAD

**Issue by sakurasakura1996** [Lornatang/YOLOv4-PyTorch#1]
@Lornatang 你好，我在Yolov5的issue中看到了你的仓库，我想把Yolov5的backbone改成CSPdarknet或者resnet，但是不知道该怎么改，我在你的仓库中看到了Yolov4.yaml，除了backbone的配置其他和Yolov5很相似，请问如果用你的backbone配置参数替换yolov5中的参数可行吗，如果替换成功，预训练模型可以直接使用Yolov4权重的前半部分吗

**Comment by Lornatang** [comment]
ok
